version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build completed. No compilation needed for Flask.

artifacts:
  files:
    - application.py
    - requirements.txt
    - templates/**/*
    - src/**/*
    - artifact/**/*
    - .ebextensions/**/*
